apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: confiance-en-soi
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpassword" # echo "rootpassword" | base64 
  MYSQL_PASSWORD: "userpassword"
