apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: confiance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: imleiluspocus/confiance-front:v3
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: "http://127.0.0.1:58190"
        resources:
          requests: # Le minimum pour le bon fonctionnement du pod
            cpu: 100m  # Millicore, pourcentage de puissance CPU
            memory: 128Mi
          limits: # Les ressources maximales que le pod peut utiliser
            cpu: 500m # Millicore, pourcentage de puissance CPU
            memory: 600Mi # Mébioctet

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: confiance
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30000
  type: NodePort
