apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: confiance-en-soi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: imleiluspocus/confiance-front:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: "http://127.0.0.1:58190"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: confiance-en-soi
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30000
  type: NodePort
