name: Workflow CI/CD

on:
  push:
    branches: [ main, workflows ]

jobs:
  say_hello:
    runs-on: ubuntu-latest 

    steps:
      - name: Afficher un message dans la console
        run: echo "Hello world, bientôt une CI ici!"
      
      - name: Pull Docker image
        run: docker pull imleiluspocus/confiance-back:v3
      
      - name: Run tests inside the Docker container
        run: |
          docker run --rm \
            imleiluspocus/confiance-back:v3 \
            sh -c "npm install && npm run test"